name: Generate Isometric Commit Calendar

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week (Sunday at midnight)
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        timeout-minutes: 15  # Add a timeout for the checkout step

      - name: Setup Metrics Plugin
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # GitHub token with repo scope
          plugin_isocalendar: yes  # Enable the isometric calendar plugin
          plugin_isocalendar_duration: half-year  # Reduce to half-year to improve performance
          filename: metrics.plugin.isocalendar.svg  # Output file name
        timeout-minutes: 15  # Add a timeout for the metrics plugin step

      - name: Upload Isometric Commit Calendar
        uses: actions/upload-artifact@v3
        with:
          name: isometric-calendar  # Name of the artifact
          path: metrics.plugin.isocalendar.svg  # File to upload
