name: Generate Isometric Commit Calendar
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week (Sunday at midnight)
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        timeout-minutes: 10  # Set timeout to 10 minutes

      - name: Setup Metrics Plugin
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          filename: metrics.plugin.isocalendar.fullyear.svg
        timeout-minutes: 10  # Set timeout for this step too
      
      - name: Commit and Push Generated SVG
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add metrics.plugin.isocalendar.fullyear.svg
          git commit -m "Add generated isometric calendar"
          git push
